<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <DeterministicSourcePaths Condition="'$(CI)' == 'true'">true</DeterministicSourcePaths>
    <Authors>Oragon</Authors>
    <Company>Oragon</Company>
    <Copyright>Copyright © Oragon</Copyright>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/oragon/Oragon.AdaptivePool</RepositoryUrl>
  </PropertyGroup>
</Project>
